/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  active?: boolean;
  email: string;
  firstname: string;
  iban?: string;
  id?: number;
  lastname: string;
  password: string;
}
