/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDto } from '../models/user-dto';
export interface AccountDto {
  iban?: string;
  id?: number;
  user?: UserDto;
}
