/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactDto {
  email?: string;
  firstname?: string;
  iban?: string;
  id?: number;
  lastname?: string;
  userId?: number;
}
