/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskDto {
  dateDebut?: string;
  dateFin?: string;
  id?: number;
  tache?: string;
  userId?: number;
}
