/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskDto } from '../../models/task-dto';

export interface FindAllByUserId1$Params {
  'user-id': number;
}

export function findAllByUserId1(http: HttpClient, rootUrl: string, params: FindAllByUserId1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TaskDto>>> {
  const rb = new RequestBuilder(rootUrl, findAllByUserId1.PATH, 'get');
  if (params) {
    rb.path('user-id', params['user-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TaskDto>>;
    })
  );
}

findAllByUserId1.PATH = '/tasks/users/{user-id}';
